# Generated by Django 5.0.6 on 2024-07-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("literary_works", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="literarywork",
            name="image",
            field=models.ImageField(blank=True, upload_to="literary - works_images/"),
        ),
        migrations.AddField(
            model_name="literarywork",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
