# Generated by Django 5.0.6 on 2024-07-20 08:59

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='security_question_1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='security_question_2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='security_question_3',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='history_data',
        ),
        migrations.AddField(
            model_name='userhistory',
            name='action',
            field=models.CharField(default='default_action', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_name', models.CharField(max_length=255)),
                ('prompt_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.prompttype')),
            ],
        ),
    ]
