# Generated by Django 5.0.6 on 2024-08-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="favorite_book",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="secret_question",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
