# Generated by Django 5.0.6 on 2024-07-20 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_security_answer_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_genre',
        ),
        migrations.RemoveField(
            model_name='browsinghistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='myprompt',
            name='prompt_type',
        ),
        migrations.RemoveField(
            model_name='myprompt',
            name='reader',
        ),
        migrations.RemoveField(
            model_name='myprompttype',
            name='reader',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='security_answer',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_security_answer', message='Security answer must be in lowercase letters only.', regex='^[a-z]+$')]),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='BrowsingHistory',
        ),
        migrations.DeleteModel(
            name='MyPrompt',
        ),
        migrations.DeleteModel(
            name='MyPromptType',
        ),
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
