# Generated by Django 5.0.6 on 2024-07-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_book_book_author_remove_book_book_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='security_answer',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Prompt',
        ),
        migrations.DeleteModel(
            name='PromptType',
        ),
    ]
