# Generated by Django 5.0.6 on 2024-07-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_managers_customuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='security_answer',
        ),
        migrations.AddField(
            model_name='customuser',
            name='secret_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='secret_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='favorite_book',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
