# Generated by Django 5.0.6 on 2024-07-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_book',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
