# Generated by Django 5.0.6 on 2024-08-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tbr_place", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="readingprogress",
            name="goal",
        ),
        migrations.DeleteModel(
            name="ReadingGoal",
        ),
        migrations.DeleteModel(
            name="ReadingProgress",
        ),
    ]
