# Generated by Django 5.0.6 on 2024-07-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbr_place', '0002_alter_prompt_prompt_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt_name',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='myprompttype',
            unique_together={('myprompt_type_name', 'reader')},
        ),
    ]
